2023-12-19 01:31:50.127 | INFO     | scripts.pipeline_class:<module>:28 - Running on win32
2023-12-19 01:31:50.127 | INFO     | scripts.pipeline_ai:<module>:27 - Running on win32
2023-12-19 01:31:50.127 | INFO     | scripts.pipeline_ai:<module>:27 - Running on win32
2023-12-19 01:31:50.127 | INFO     | scripts.pipeline_class:process:190 - hindi process started
2023-12-19 01:31:50.127 | INFO     | scripts.pipeline_class:process:190 - hindi process started
2023-12-19 01:31:50.127 | INFO     | scripts.pipeline_class:__init__:33 - Class initialized
2023-12-19 01:31:50.127 | INFO     | scripts.pipeline_class:__init__:33 - Class initialized
2023-12-19 01:31:50.127 | INFO     | scripts.pipeline_class:__init__:39 - Device: cpu
2023-12-19 01:31:50.127 | INFO     | scripts.pipeline_class:__init__:39 - Device: cpu
2023-12-19 01:31:50.143 | INFO     | scripts.pipeline_class:start:117 - Starting Pipeline
2023-12-19 01:31:50.143 | INFO     | scripts.pipeline_class:start:117 - Starting Pipeline
2023-12-19 01:31:50.143 | INFO     | scripts.pipeline_class:translated_sub:68 - Creating Subtitles
2023-12-19 01:31:50.143 | INFO     | scripts.pipeline_class:translated_sub:68 - Creating Subtitles
2023-12-19 01:31:50.143 | INFO     | scripts.pipeline_class:translated_sub:73 - Reaching out to translator function...
2023-12-19 01:31:50.143 | INFO     | scripts.pipeline_class:translated_sub:73 - Reaching out to translator function...
2023-12-19 01:47:15.703 | ERROR    | scripts.pipeline_class:translate:49 - Error occurred while loading the model/tokenizer: (MaxRetryError('HTTPSConnectionPool(host=\'cdn-lfs.huggingface.co\', port=443): Max retries exceeded with url: /repos/6e/ef/6eef128ace768b50a05cfccb07249581231dafe7b91ae38b6d142cbc66dab00d/c266c2cfd19758b6d09c1fc31ecdf1e485509035f6b51dfe84f1ada83eefcc42?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27pytorch_model.bin%3B+filename%3D%22pytorch_model.bin%22%3B&response-content-type=application%2Foctet-stream&Expires=1703188936&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwMzE4ODkzNn19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9yZXBvcy82ZS9lZi82ZWVmMTI4YWNlNzY4YjUwYTA1Y2ZjY2IwNzI0OTU4MTIzMWRhZmU3YjkxYWUzOGI2ZDE0MmNiYzY2ZGFiMDBkL2MyNjZjMmNmZDE5NzU4YjZkMDljMWZjMzFlY2RmMWU0ODU1MDkwMzVmNmI1MWRmZTg0ZjFhZGE4M2VlZmNjNDI~cmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj0qJnJlc3BvbnNlLWNvbnRlbnQtdHlwZT0qIn1dfQ__&Signature=YyOtelN7beuE8-vC5MCo7d6er7RLcBbE-TsbfEkMxE6pXDVbBdrOJCVl0VpPnMHox6bGo4WEkqy3II3-OpL8zjhiijU4CYRihCZAsqwfzpHxQoGv7uE1vHrYgk~tI3P38c3OFVLb6NyKA7ahapNPkmo8FOmo0sHFHAvT37TT9GkMiixbzHeUgGqaa~ux3evjpPFQpfq8d4vtsKr2o64Xi3sqUgmKvJfGxrJJUYxX-dzFddVYDalm3o29ZsLhJxu42ZXl4sMsGygPM-oPl7NETJwlklNWvcc9CTDLNmh4fcWlDn6TkBtKezamUwXPFMd39wpSRewUd~MMOOSRHOpnkw__&Key-Pair-Id=KVTP0A1DKRTAX (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000133A3179A10>: Failed to resolve \'cdn-lfs.huggingface.co\' ([Errno 11001] getaddrinfo failed)"))'), '(Request ID: d6dceece-da4d-4fb0-927e-a8f2d69e764a)')
2023-12-19 01:47:15.703 | ERROR    | scripts.pipeline_class:translate:49 - Error occurred while loading the model/tokenizer: (MaxRetryError('HTTPSConnectionPool(host=\'cdn-lfs.huggingface.co\', port=443): Max retries exceeded with url: /repos/6e/ef/6eef128ace768b50a05cfccb07249581231dafe7b91ae38b6d142cbc66dab00d/c266c2cfd19758b6d09c1fc31ecdf1e485509035f6b51dfe84f1ada83eefcc42?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27pytorch_model.bin%3B+filename%3D%22pytorch_model.bin%22%3B&response-content-type=application%2Foctet-stream&Expires=1703188936&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwMzE4ODkzNn19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9yZXBvcy82ZS9lZi82ZWVmMTI4YWNlNzY4YjUwYTA1Y2ZjY2IwNzI0OTU4MTIzMWRhZmU3YjkxYWUzOGI2ZDE0MmNiYzY2ZGFiMDBkL2MyNjZjMmNmZDE5NzU4YjZkMDljMWZjMzFlY2RmMWU0ODU1MDkwMzVmNmI1MWRmZTg0ZjFhZGE4M2VlZmNjNDI~cmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj0qJnJlc3BvbnNlLWNvbnRlbnQtdHlwZT0qIn1dfQ__&Signature=YyOtelN7beuE8-vC5MCo7d6er7RLcBbE-TsbfEkMxE6pXDVbBdrOJCVl0VpPnMHox6bGo4WEkqy3II3-OpL8zjhiijU4CYRihCZAsqwfzpHxQoGv7uE1vHrYgk~tI3P38c3OFVLb6NyKA7ahapNPkmo8FOmo0sHFHAvT37TT9GkMiixbzHeUgGqaa~ux3evjpPFQpfq8d4vtsKr2o64Xi3sqUgmKvJfGxrJJUYxX-dzFddVYDalm3o29ZsLhJxu42ZXl4sMsGygPM-oPl7NETJwlklNWvcc9CTDLNmh4fcWlDn6TkBtKezamUwXPFMd39wpSRewUd~MMOOSRHOpnkw__&Key-Pair-Id=KVTP0A1DKRTAX (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000133A3179A10>: Failed to resolve \'cdn-lfs.huggingface.co\' ([Errno 11001] getaddrinfo failed)"))'), '(Request ID: d6dceece-da4d-4fb0-927e-a8f2d69e764a)')
2023-12-19 01:47:15.705 | ERROR    | scripts.pipeline_class:translated_sub:90 - Error while translating subtitles:1
2023-12-19 01:47:15.705 | ERROR    | scripts.pipeline_class:translated_sub:90 - Error while translating subtitles:1
2023-12-19 01:47:15.705 | ERROR    | scripts.pipeline_class:start:131 - Error while running pipeline:1
2023-12-19 01:47:15.705 | ERROR    | scripts.pipeline_class:start:131 - Error while running pipeline:1
